### ISSUE TITLE
오타 문의드립니다.

### ISSUE THREAD

**Issue by happy-yeachan** [Jinpyo-Ahn/typescript#1]
<img width="249" alt="image" src="https://github.com/Jinpyo-Ahn/typescript/assets/21968811/862c695c-298a-4515-8c25-0b68b10e7aba">

잘못된 표기가 있네요

**Comment by Jinpyo-An** [comment]
title 프로퍼티의 값은 알맞게(?) 작성한 거 같고, done 프로퍼티의 진위 값이 잘못 작성된 것을 확인하였습니다. 귀여운 게 맞으니 true가 맞습니다. 문의 감사합니다

**Comment by happy-yeachan** [comment]
그렇군요 허허 안진표 == cute 이 논리 명제가 True일줄은 상상도 하지 못했네요.
좋은 정보 감사합니다.
